### ISSUE TITLE
Mailman mass-addition default behavior must be changed from `subscript` to `invite`

### ISSUE THREAD

**Issue by ghost** [terencehonles/mailman#1]
We always assume the default settings are safe, but that is not the case with Mailman!

Why do you have the `subscript` as the default choice with mass addition? It should be changed to `invite`, and maybe with an extra warning when the user tries to switch to subscribe! Your default behavior is troublesome 😕  and can cause huge issues and a lot of anger (see here: Open-3D/Open-3D#34 for an example).
After all, Mailman interface is not user friendly, and it is rather hard to see all the options, and we tend to use the defaults..

**Comment by skade** [comment]
This is a random repository of mailman, not touched since 2012, the official repository is at https://gitlab.com/mailman.

**Comment by ghost** [comment]
@skade This is very kind of you, Thanks a lot
